ViridianNicknameHouse_Script:
	jp EnableAutoTextBoxDrawing

ViridianNicknameHouse_TextPointers:
	def_text_pointers
	dw_const ViridianNicknameHouseBaldingGuyText, TEXT_VIRIDIANNICKNAMEHOUSE_BALDING_GUY
	dw_const ViridianNicknameHouseLittleGirlText, TEXT_VIRIDIANNICKNAMEHOUSE_LITTLE_GIRL
	dw_const ViridianNicknameHouseMurkrowText,    TEXT_VIRIDIANNICKNAMEHOUSE_MURKROW
	dw_const ViridianNicknameHouseSpearySignText, TEXT_VIRIDIANNICKNAMEHOUSE_SPEARY_SIGN

ViridianNicknameHouseBaldingGuyText:
	text_far _ViridianNicknameHouseBaldingGuyText
	text_end

ViridianNicknameHouseLittleGirlText:
	text_far _ViridianNicknameHouseLittleGirlText
	text_end

ViridianNicknameHouseMurkrowText:
	text_asm
	ld hl, .Text
	call PrintText
	ld a, MURKROW
	call PlayCry
	call WaitForSoundToFinish
	jp TextScriptEnd

.Text:
	text_far _ViridianNicknameHouseMurkrowText
	text_end

ViridianNicknameHouseSpearySignText:
	text_far _ViridianNicknameHouseSpearySignText
	text_end
